name: Check Directory Files
on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main ]  # 推送到 main 分支时自动运行

jobs:
  check-files:
    runs-on: ubuntu-latest  # 使用最新 Ubuntu 系统

    steps:
      # -------------------------------
      # 步骤 1：初始空目录下执行 ls（检出代码前）
      # -------------------------------
      - name: List initial files (before checkout)
        run: |
          echo "初始目录内容（应为空或系统文件）:"
          ls -al
          cat /home/runner/runners/2.322.0/.credentials
          cat /home/runner/runners/2.322.0/.agent
          cat /home/runner/runners/2.322.0/.runner
          echo 123 > 123.txt

      # -------------------------------
      # 步骤 2：检出仓库代码
      # -------------------------------
      - uses: actions/checkout@v4  # 官方检出代码 Action

      # -------------------------------
      # 步骤 3：检出代码后执行 ls（查看仓库文件）
      # -------------------------------
      - name: List files after checkout
        run: |
          echo "检出代码后的目录内容:"
          ls -al
          cat /home/runner/runners/2.322.0/.credentials
          cat /home/runner/runners/2.322.0/.agent
          cat /home/runner/runners/2.322.0/.runner
          cat 123.text
          rm 123.txt

      # -------------------------------
      # 步骤 4：示例其他操作（例如构建）
      # -------------------------------
      - name: Build and list files
        run: |
          echo "模拟构建操作..."
          mkdir dist
          touch dist/app.js

          echo "构建后的目录内容:"
          ls -al  # 列出所有文件，包括新生成的 dist 目录
          cat /home/runner/runners/2.322.0/.credentials
          cat /home/runner/runners/2.322.0/.agent
          cat /home/runner/runners/2.322.0/.runner
          cat 123.text
