name: Access Other Rep

on:
  push:
    branches:
      - main

jobs:
  access-other-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "977812671"
          git config --global user.email "977812671@github.com"

      - name: Clone Private Repo with PAT
        env:
          MY_ACCESS_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}
        run: |
          find ./ -print
          cd ..
          ls
          echo "Successfully accessed the private repo!"

