# 文件路径: .github/workflows/secure-pipeline.yml
name: Security-Hardened CI/CD
on:
  push:
    branches: [ "main", "release/*" ]
  pull_request:
    branches: [ "main" ]

# -------------------- 全局安全配置 --------------------
permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  id-token: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none

# -------------------- 作业级加固 --------------------
jobs:
  build:
    name: Hardened Build
    runs-on: ubuntu-latest
    environment: production

    env:
      ACTIONS_ALLOWED_EGRESS: "api.github.com, pkg-registry.example.com, required-cdn.com"
      GITHUB_TOKEN: ${{ secrets.READ_ONLY_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 关键修复：仅在 pull_request 事件中运行依赖审查
      - name: Dependency Audit
        if: github.event_name == 'pull_request'  # 添加事件类型判断
        uses: actions/dependency-review-action@v3
        with:
          base-ref: ${{ github.base_ref }}  # 显式指定基准分支
          head-ref: ${{ github.head_ref }}   # 显式指定来源分支
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Build with Security Context
        run: |
          docker build --security-opt no-new-privileges -t app-image .
        env:
          DOCKER_CONTENT_TRUST: 1

      - name: Upload Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/
          retention-days: 1
